server:
  port: 8090

spring:
  datasource:
    hikari:
      maximum-pool-size: 4

mybatis:
  type-aliases-package: card.mng.dto.model #testModel 위치
  # typehandler - https://mybatis.org/mybatis-3/ko/configuration.html#typeHandlers
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: card/mng/mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
  level:
    root: INFO
    card:
      mng: DEBUG